site_name: SteptronOss
repo_url: https://github.com/Randomizez/SteptronOss
site_url: https://Randomizez.github.io/SteptronOss
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: stepfun-ai
edit_uri: edit/main/docs/
repo_name: Randomizez/SteptronOss
copyright: Maintained by <a href="https://Randomizez.com">Randomizez</a>.

nav:
  - Home: index.md
  - Modules: MODULES.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["steptronoss"]
          options:
            heading_level: 3
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Randomizez/SteptronOss
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/SteptronOss

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
