[project]
name = "SteptronOss"
version = "0.0.1"
description = "This is a template repository for Python projects that use uv for their dependency management."
authors = [{ name = "stepfun-ai", email = "henryzhou@stepfun.com" }]
readme = "README.md"
keywords = ['python']
requires-python = ">=3.10,<4.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "aiohttp",
    "aioredis",
    "emoji",
    "boto3",
    "configurize==0.2.0",
    "diskcache>=5.6.3",
    "einops",
    "fastapi",
    "hjson",
    "ijson",
    "loguru",
    "megfile",
    "msgpack",
    "nltk",
    "numpy",
    "packaging",
    "pyyaml",
    "redis",
    "safetensors",
    "setuptools",
    "syllapy",
    "tabulate",
    "torch>=2.9.0",
    "tqdm",
    "transformers",
    "triton>=3.5.0",
    "uvicorn",
    "wandb",
    "httpx",
    "pip>=25.3",
    "vllm>=0.16",
    "tensorboard>=2.20.0",
    "asciichartpy>=1.5.25",
]

[tool.uv]
required-version = ">=0.8.4"

[tool.uv.sources]
nv-grouped-gemm = { git = "https://github.com/fanshiqing/grouped_gemm.git" }

[project.urls]
Homepage = "https://Randomizez.github.io/SteptronOss/"
Repository = "https://github.com/Randomizez/SteptronOss"
Documentation = "https://Randomizez.github.io/SteptronOss/"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pre-commit>=4.5.0",
    "tox-uv>=1.29.0",
    "deptry>=0.24.0",
    "mypy>=1.19.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.8",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "mkdocstrings[python]>=1.0.0",
    "black",
    "isort",
    "py-spy",
    "debugpy",
    "ipython>=8.38.0",
    "nvitop>=1.6.2",
]

[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["steptronoss"]

[tool.mypy]
files = ["steptronoss"]
disable_error_code = ["assignment"]
disallow_any_unimported = true
warn_unused_ignores = true
show_error_codes = true

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "cpu: CPU-only tests",
    "gpu: GPU-only tests",
    "node2: requires 2 processes (torchrun --nproc-per-node=2)",
    "xdist_group(name): serialize tests that share the same torchrun resources",
]

[tool.ruff]
target-version = "py310"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    "E501",    # LineTooLong
    "E731",    # DoNotAssignLambda
    "S101",    # assert
    "TRY003",  # raise-vanilla-args
    "RUF003",  # ambiguous-unicode-character-comment
    "F401",    # unused-import
    "SIM102",  # collapsible-if
    "C408",    # unnecessary-collection-call
    "SIM108",  # if-else-block-instead-of-if-exp
    "C901",    # complex-structure
    "RUF002",  # ambiguous-unicode-character-docstring
    "RUF012",  # mutable-class-default
    "B905",    # zip-without-explicit-strict
    "E402",    # module-import-not-at-top-of-file
    "A002",    # builtin-argument-shadowing
    "E722",    # bare-except
    "RUF005",  # collection-literal-concatenation
    "S301",    # suspicious-pickle-usage
    "RUF001",  # ambiguous-unicode-character-string
    "RUF059",  # unused-unpacked-variable
    "S110",    # try-except-pass
    "TRY002",  # raise-vanilla-class
    "A001",    # builtin-variable-shadowing
    "S311",    # suspicious-non-cryptographic-random-usage
    "SIM105",  # suppressible-exception
    "F403",    # undefined-local-with-import-star
    "TRY300",  # try-consider-else
    "B006",    # mutable-argument-default
    "B904",    # raise-without-from-inside-except
    "F821",    # undefined-name
    "RUF015",  # unnecessary-iterable-allocation-for-first-element
    "TRY201",  # verbose-raise
    "B028",    # no-explicit-stacklevel
    "E741",    # ambiguous-variable-name
    "S104",    # hardcoded-bind-all-interfaces
    "SIM115",  # open-file-with-context-handler
    "A004",    # builtin-import-shadowing
    "PGH003",  # blanket-type-ignore
    "S108",    # hardcoded-temp-file
    "TRY301",  # raise-within-try
    "UP008",   # super-call-with-parameters
    "A006",    # builtin-lambda-argument-shadowing
    "B011",    # assert-false
    "B015",    # useless-comparison
    "B027",    # empty-method-without-abstract-decorator
    "F811",    # redefined-while-unused
    "S105",    # hardcoded-password-string
    "S324",    # hashlib-insecure-hash-function
    "S506",    # unsafe-yaml-load
    "S603",    # subprocess-without-shell-equals-true
    "S607",    # start-process-with-partial-path
    "SIM211",  # if-expr-with-false-true
    "T100",    # debugger
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["steptronoss"]

[tool.isort]
profile = "black"
line_length = 120
py_version = 310
known_first_party = "steptronoss"
known_third_party = "wandb"
