[project]
name = "SteptronOss"
version = "0.0.1"
description = "This is a template repository for Python projects that use uv for their dependency management."
authors = [{ name = "stepfun-ai", email = "henryzhou@stepfun.com" }]
readme = "README.md"
keywords = ['python']
requires-python = ">=3.10,<4.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "aiohttp",
    "aioredis",
    "boto3",
    "configurize",
    "einops",
    "fastapi",
    "hjson",
    "ijson",
    "loguru",
    "megfile",
    "msgpack",
    "numpy",
    "packaging",
    "pyyaml",
    "redis",
    "safetensors",
    "setuptools",
    "tabulate",
    "torch==2.8.0",
    "tqdm",
    "transformers",
    "triton==3.4.0",
    "uvicorn",
    "wandb",
    "httpx",
    "pip>=25.3",
]



[tool.uv.sources]
nv-grouped-gemm = { git = "https://github.com/fanshiqing/grouped_gemm.git" }

[project.urls]
Homepage = "https://Randomizez.github.io/SteptronOss/"
Repository = "https://github.com/Randomizez/SteptronOss"
Documentation = "https://Randomizez.github.io/SteptronOss/"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pre-commit>=4.5.0",
    "tox-uv>=1.29.0",
    "deptry>=0.24.0",
    "mypy>=1.19.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.8",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "mkdocstrings[python]>=1.0.0",
    "black",
    "isort",
    "py-spy",
    "debugpy",
    "ipython>=8.38.0",
    "nvitop>=1.6.2",
]

[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["steptronoss"]

[tool.mypy]
files = ["steptronoss"]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "cpu: CPU-only tests",
    "gpu: GPU-only tests",
    "node2: requires 2 processes (torchrun --nproc-per-node=2)",
]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["steptronoss"]

[tool.isort]
profile = "black"
line_length = 120
py_version = 310
known_first_party = "steptronoss"
known_third_party = "wandb"
