from loguru import logger

from steptronoss.data.recipe import CompiledDataRecipe, DataRecipe
from steptronoss.exp.abstract import BaseExp
from steptronoss.exp.sft import SFTDatasetsConfig


class CompliableDatasetsConfig(SFTDatasetsConfig):
    def get_template(self):
        from steptron.tokenizer.qwen_tokenizers import (
            Qwen3MainlineVLLMMultiTurnTokenizer,
        )

        from steptronoss.data.chat_templates.qwen_template import (
            Qwen3MultiTurnMaskSFTTemplate,
        )

        template = Qwen3MultiTurnMaskSFTTemplate(Qwen3MainlineVLLMMultiTurnTokenizer())
        return template

    def get_recipe(self) -> DataRecipe:
        from playground.data.sft.reasoning_GCMKSTIDF_sft_stage1_1203 import (
            SFT_1203_BASE_DATA_DS0p1_RECIPE,
        )

        return SFT_1203_BASE_DATA_DS0p1_RECIPE

    def get_dataset(self, filelist, template):
        from steptronoss.data.datasets.stepchat_dataset import StepChatJsonDataset

        return StepChatJsonDataset(filelist=filelist, template=template)

    def build_datasets(self):
        dataset_epochs: dict[str, tuple[list, float]] = {}
        recipe = self.get_recipe()
        template = self.get_template()
        for k in recipe.domains:
            dataset = self.get_dataset(recipe.domains[k].files, template)
            dataset_epochs[k] = (dataset, recipe.epochs[k])
        return dataset_epochs


class CompiledDatasetsConfig(SFTDatasetsConfig):
    compiled_recipe: CompiledDataRecipe

    def build_datasets(self):
        from steptronoss.data.datasets.compile_dataset import CompiledDataset

        dataset_epochs: dict[str, tuple[list, float]] = {}
        for k, compiled_path in self.compiled_recipe.domains.items():
            dataset = CompiledDataset(compiled_path)
            dataset_epochs[k] = (dataset, self.compiled_recipe.epochs[k])
        return dataset_epochs


class Exp(BaseExp):

    src_data_cfg: CompliableDatasetsConfig

    compile_path: str
    """where to save compiled datasets."""

    save_compiled_cfg_to: str
    """Where to write CompiledDataRecipe."""

    def _compile_domain(
        self,
        domain_files: list,
        save_path: str,
    ) -> str:
        from steptronoss.data.datasets.compile_dataset import compile_dataset

        template = self.src_data_cfg.get_template()
        dataset = self.src_data_cfg.get_dataset(domain_files, template)

        return compile_dataset(dataset, save_path, sample_meta_extractor=lambda x: len(x["tokens"]))

    def compile(self) -> str:
        """Compile self.src_data_cfg to a compiled recipe. The recipe will be saved as a python file."""
        import os

        import megfile

        recipe = self.src_data_cfg.get_recipe()
        domain_items = list(recipe.domains.items())
        compiled_domains = dict()
        if not domain_items:
            raise ValueError("No datasets to compile.")

        for name, domain in recipe.domains.items():
            compiled_domains[name] = self._compile_domain(
                domain_files=domain.files,
                save_path=megfile.smart_path_join(self.compile_path, name),
            )
            logger.info(f"Successfully compiled domain: {name}")

        out_dir = os.path.dirname(self.save_compiled_cfg_to)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)

        lines = [
            "# Auto-generated by playground/tools/compile_recipe.py",
            "from steptronoss.data.recipe import CompiledDataRecipe",
            "from playground.tools.compile_recipe import CompiledDatasetsConfig",
            "",
            "compiled_recipe = CompiledDataRecipe(",
            "    domains={",
        ]
        for name, path in compiled_domains.items():
            lines.append(f"        {name!r}: {path!r},")
        lines += [
            "    },",
            "    epochs={",
        ]
        for name, epoch in recipe.epochs.items():
            lines.append(f"        {name!r}: {epoch},")
        lines += [
            "    },",
            ")",
            "",
            "",
            "class DatasetsConfig(CompiledDatasetsConfig):",
            "    compiled_recipe = compiled_recipe",
            "",
        ]
        copypaste = "\n".join(lines)
        with open(self.save_compiled_cfg_to, "w", encoding="utf-8") as f:
            f.write(copypaste)
        logger.info(f"Generated compiled recipe, code copypaste:\n\n{copypaste}")

        return self.save_compiled_cfg_to


if __name__ == "__main__":
    exp = Exp()
    exp.src_data_cfg = CompliableDatasetsConfig()
    exp.compile_path = "/mnt/shared-storage/tenant/zhy/cp_260116/"
    exp.save_compiled_cfg_to = "./compiled_260116.py"
    exp.compile()
