from loguru import logger

from steptronoss.data.recipe import CompiledDataRecipe, DataRecipe
from steptronoss.exp.sft import SFTDatasetsConfig


class CompliableDatasetsConfig(SFTDatasetsConfig):
    def get_template(self):
        pass

    def get_recipe(self) -> DataRecipe:
        pass

    def get_dataset(self, filelist, template):
        from steptronoss.data.datasets.stepchat_dataset import StepChatJsonDataset

        return StepChatJsonDataset(filelist=filelist, template=template)

    def build_datasets(self):
        dataset_epochs: dict[str, tuple[list, float]] = {}
        recipe = self.get_recipe()
        template = self.get_template()
        for k in recipe.domains:
            dataset = self.get_dataset(recipe.domains[k], template)
            dataset_epochs[k] = (dataset, recipe.epochs[k])
        return dataset_epochs

    def _compile_domain(
        self,
        domain_files: list,
        save_path: str,
    ) -> str:
        from steptronoss.data.datasets.compile_dataset import compile_dataset

        template = self.get_template()
        dataset = self.get_dataset(domain_files, template)

        return compile_dataset(dataset, save_path, sample_meta_extractor=lambda x: len(x["tokens"]))

    def compile(self, compile_path) -> str:
        """Compile self.src_data_cfg to a compiled recipe. The recipe will be saved as a python file."""
        import os

        import megfile

        recipe = self.get_recipe()
        domain_items = list(recipe.domains.items())
        compiled_domains = dict()
        if not domain_items:
            raise ValueError("No datasets to compile.")

        for name, domain in recipe.domains.items():
            compiled_domains[name] = self._compile_domain(
                domain_files=domain,
                save_path=megfile.smart_path_join(compile_path, name),
            )
            logger.info(f"Successfully compiled domain: {name}")

        lines = [
            "# Auto-generated by playground/tools/compile_recipe.py",
            "from steptronoss.data.recipe import CompiledDataRecipe",
            "from playground.tools.compile_recipe import CompiledDatasetsConfig",
            "",
            "",
            "class DatasetsConfig(CompiledDatasetsConfig):",
            "    compiled_recipe = CompiledDataRecipe(",
            "        domains={",
        ]
        for name, path in compiled_domains.items():
            lines.append(f"            {name!r}: {path!r},")
        lines += [
            "        },",
            "        epochs={",
        ]
        for name, epoch in recipe.epochs.items():
            lines.append(f"            {name!r}: {epoch},")
        lines += [
            "        },",
            "    )",
            "",
        ]
        copypaste = "\n".join(lines)
        logger.info(f"Generated compiled recipe, code copypaste:\n\n{copypaste}")


class CompiledDatasetsConfig(SFTDatasetsConfig):
    compiled_recipe: CompiledDataRecipe

    def build_datasets(self):
        from steptronoss.data.datasets.compile_dataset import CompiledDataset

        dataset_epochs: dict[str, tuple[list, float]] = {}
        for k, compiled_path in self.compiled_recipe.domains.items():
            dataset = CompiledDataset(compiled_path)
            dataset_epochs[k] = (dataset, self.compiled_recipe.epochs[k])
        return dataset_epochs
