# Auto-generated by playground/tools/compile_recipe.py
from playground.tools.compile_recipe import CompiledDatasetsConfig
from steptronoss.data.recipe import CompiledDataRecipe

compiled_recipe = CompiledDataRecipe(
    domains={
        "code": "/mnt/shared-storage/tenant/zhy/cp_260116/code",
        "math": "/mnt/shared-storage/tenant/zhy/cp_260116/math",
        "science": "/mnt/shared-storage/tenant/zhy/cp_260116/science",
        "swe": "/mnt/shared-storage/tenant/zhy/cp_260116/swe",
        "swe_agentic": "/mnt/shared-storage/tenant/zhy/cp_260116/swe_agentic",
        "toolcall": "/mnt/shared-storage/tenant/zhy/cp_260116/toolcall",
        "general": "/mnt/shared-storage/tenant/zhy/cp_260116/general",
        "logic": "/mnt/shared-storage/tenant/zhy/cp_260116/logic",
        "dr": "/mnt/shared-storage/tenant/zhy/cp_260116/dr",
    },
    epochs={
        "code": 3,
        "math": 2,
        "science": 2,
        "swe": 2,
        "swe_agentic": 2,
        "toolcall": 2,
        "general": 2,
        "logic": 3,
        "dr": 3,
    },
)


class DatasetsConfig(CompiledDatasetsConfig):
    compiled_recipe = compiled_recipe
